tasks/urls.py
from django.conf.urls import url

from tasks.views import (
    TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView,
    ListDetailView, ListListView, ListCreateView, ListUpdateView,
    ListWithTasksCreateView, ListWithTasksUpdateView
)

app_name = 'tasks'

urlpatterns = [
    url(r'^$', TaskListView.as_view(), name='task_list'),
    url(r'^(?P<pk>\d+)/$', TaskDetailView.as_view(), name='task_detail'),
    url(r'^create/$', TaskCreateView.as_view(), name='task_create'),
    url(r'^(?P<pk>\d+)/edit/$', TaskUpdateView.as_view(), name='task_edit'),

    url(r'^list/(?P<pk>\d+)/$', ListDetailView.as_view(), name='list_detail'),
    url(r'^list/create/$', ListCreateView.as_view(), name='list_create'),
    url(
        r'^list/(?P<pk>\d+)/edit/$', ListUpdateView.as_view(),
        name='list_edit'
    ),
    url(r'^lists/$', ListListView.as_view(), name='list_list'),
    url(
        r'^list/with-tasks/$', ListWithTasksCreateView.as_view(),
        name='list_tasks_create'
    ),
    url(
        r'^list/with-tasks/(?P<pk>\d+)/edit/$',
        ListWithTasksUpdateView.as_view(),
        name='list_tasks_edit'
    ),
]

todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^tasks/', include('tasks.urls')),
    url(r'^tasks-traditional/', include('tasks.traditional_urls')),

    # Django Authentication
    url(r'^account/', include('django.contrib.auth.urls')),

    # Django Admin
    url(r'^admin/', admin.site.urls),
]

tasks/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext as _


class List(models.Model):
    name = models.CharField(_('Name'), null=False, blank=False, max_length=255)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('List')
        verbose_name_plural = _('Lists')

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('')


class Task(models.Model):
    LOWEST = 1
    LOW = 2
    MEDIUM = 3
    HIGH = 4
    HIGHEST = 5

    PRIORITY_CHOICES = [
        (LOWEST, _('Lowest')),
        (LOW, _('Low')),
        (MEDIUM, _('Medium')),
        (HIGH, _('High')),
        (HIGHEST, _('Highest')),
    ]

    name = models.CharField(_('Name'), null=False, blank=False, max_length=255)
    description = models.TextField(_('Description'), null=True, blank=True)
    due_date = models.DateTimeField(_('Due Date'), null=True, blank=True)
    priority = models.IntegerField(
        _('Priority'), choices=PRIORITY_CHOICES,
        null=False, blank=False, default=LOWEST
    )
    todo_list = models.ForeignKey(
        List, verbose_name=_('List'), null=True, blank=True
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('')

    def get_priority(self):
        for pair in self.PRIORITY_CHOICES:
            if self.priority == pair[0]:
                return pair[1]

        return self.priority

tasks/forms.py
from django import forms

from extra_views import InlineFormSet

from tasks.models import Task, List


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['author', 'created_at', 'updated_at']


class TasksInline(InlineFormSet):
    model = Task


class ListForm(forms.ModelForm):
    class Meta:
        model = List
        exclude = ['author', 'created_at', 'updated_at']

tasks/views.py
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from extra_views import (
    CreateWithInlinesView, UpdateWithInlinesView
)

from tasks.models import Task, List
from tasks.forms import TaskForm, TasksInline, ListForm


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = 'tasks/task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        return Task.objects.filter(author=self.request.user)


class TaskDetailView(generic.DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'
    context_object_name = 'task'

    def get_queryset(self):
        return Task.objects.filter(author=self.request.user)


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()

        return super(generic.CreateView, self).form_valid(form)


class TaskUpdateView(generic.UpdateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

    def get_queryset(self):
        return Task.objects.filter(author=self.request.user)


class ListDetailView(generic.DetailView):
    model = List
    template_name = 'tasks/list_detail.html'
    context_object_name = 'todolist'

    def get_queryset(self):
        return List.objects.filter(author=self.request.user)


class ListWithTasksCreateView(CreateWithInlinesView):
    model = List
    form_class = ListForm
    inlines = [TasksInline]
    template_name = 'tasks/list_form_with_inlines.html'

    def get_success_url(self):
        return reverse_lazy('tasks:list_list')

    def forms_valid(self, form, inlines):
        """
        If the form and formsets are valid, save the associated models.
        """
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()

        for formset in inlines:
            formset.save()
        return HttpResponseRedirect(self.get_success_url())


class ListWithTasksUpdateView(UpdateWithInlinesView):
    model = List
    form_class = ListForm
    inlines = [TasksInline]
    template_name = 'tasks/list_form_with_inlines.html'

    def get_success_url(self):
        return reverse_lazy('tasks:list_list')


class ListListView(generic.ListView):
    model = List
    template_name = 'tasks/list_list.html'
    context_object_name = 'lists'

    def get_queryset(self):
        return List.objects.filter(author=self.request.user)


class ListCreateView(generic.CreateView):
    model = List
    template_name = 'tasks/list_form.html'
    form_class = ListForm
    success_url = reverse_lazy('tasks:list_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()

        return super(generic.CreateView, self).form_valid(form)


class ListUpdateView(generic.UpdateView):
    model = List
    template_name = 'tasks/list_form.html'
    form_class = ListForm
    success_url = reverse_lazy('tasks:list_list')

    def get_queryset(self):
        return List.objects.filter(author=self.request.user)

tasks/templates/tasks/list_detail.html
{% extends "layout.html" %}

tasks/templates/tasks/list_form.html
{% extends "layout.html" %}

tasks/templates/tasks/list_form_with_inlines.html
{% extends "layout.html" %}

{% load i18n %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <h2>Inlines</h2>
        {% for f in inlines %}
            {{ f.as_p }}
            <hr>
        {% endfor %}
        <input type="submit" value="{% trans 'Save' %}">
    </form>
{% endblock content %}

tasks/templates/tasks/list_list.html
{% extends "layout.html" %}

{% load i18n %}

{% block content %}
    <ul>
        {% for list in lists %}
            <li>{{ list }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

tasks/templates/tasks/task_detail.html
{% extends "layout.html" %}

{% load i18n %}

{% block content %}
    <table>
        <tr>
            <td>{% trans "Task" %}:</td>
            <td>{{ task }}</td>
        </tr>
        <tr>
            <td>{% trans "Description" %}:</td>
            <td>{{ task.description }}</td>
        </tr>
        <tr>
            <td>{% trans "Priority" %}:</td>
            <td>{{ task.get_priority }}</td>
        </tr>
        <tr>
            <td>{% trans "Due date" %}:</td>
            <td>{{ task.due_date }}</td>
        </tr>
        {% if task.todo_list %}
            <tr>
                <td>{% trans "List:" %}:</td>
                <td>
                    <a href="{% url 'tasks:list_detail' task.todo_list.id %}">
                        {{ task.todo_list }}
                    </a>
                </td>
            </tr>
        {% endif %}
        <tr>
            <td><a href="{% url 'tasks:task_edit' task.id %}">{% trans "Edit" %}</a></td>
            <td></td>
        </tr>
    </table>
{% endblock content %}

tasks/templates/tasks/task_form.html
{% extends "layout.html" %}

{% load i18n %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Save' %}">
    </form>
{% endblock content %}

tasks/templates/tasks/task_list.html
{% extends "layout.html" %}

{% load i18n %}

{% block content %}
    <h1>Tasks <small>- <a href="{% url 'tasks:task_create' %}">{% trans "Add new task" %}</a></small></h1>
    <ul>
        {% for task in tasks %}
            <li><a href="{% url 'tasks:task_detail' task.id %}">{{ task }}</a> - {% trans "Priority:" %} {{ task.get_priority }} - {% trans "Due to:" %} {{ task.due_date }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

todo/templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block pagetitle %}To Do{% endblock pagetitle %}</title>

        {% block meta %}
        {% endblock meta %}

        {% block styles %}
        {% endblock styles %}

        {% block extrastyles %}
        {% endblock extrastyles %}
    </head>
    <body>
        {% block layout %}
        {% endblock layout %}

        {% block scripts %}
        {% endblock scripts %}

        {% block extrascripts %}
        {% endblock extrascripts %}
    </body>
</html>

todo/templates/layout.html
{% extends "base.html" %}

{% block layout %}
    {% block content %}

    {% endblock content %}
{% endblock layout %}